# Datathon2025_JoeyD

Dataset Claimer: 
Raw dataset is from https://drive.google.com/drive/folders/16ZSrxVzmHdv9ULz4QpT77pnI7DOLWwFO?usp=sharing, 
which locally saved as "Raw_Data.csv", but too large (more than 25MB) to upload here. 
After running Data_Cleanign.inpybcleaned dataset locally saved as "Refined_Data.csv" is generated for ML modelling but also stuck with uploading issue. 

